-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Pacientes (
IDpaciente INTEGER PRIMARY KEY,
Nome VARCHAR(200),
Sexo CHAR(1),
Foto VARCHAR(200),
Telefone VARCHAR(20),
DataNascimento DATETIME,
IDformaPag INTEGER,
Estado CHAR(2),
Cidade VARCHAR(50),
Bairro VARCHAR(50),
Rua VARCHAR(100),
Numero INTEGER
)

CREATE TABLE Especialidades (
CBO VARCHAR(10) PRIMARY KEY,
Descricao VARCHAR(50)
)

CREATE TABLE TipoExames (
IDexame INTEGER PRIMARY KEY,
DuracaoPrev SMALLDATETIME,
Nome VARCHAR(50),
Orientacoes VARCHAR(500),
Valor DECIMAL(2)
)

CREATE TABLE Medicos (
CRM VARCHAR(10) PRIMARY KEY,
Nome VARCHAR(200),
CBO VARCHAR(10),
Telefone VARCHAR(20),
Estado CHAR(2),
Cidade VARCHAR(50),
Bairro VARCHAR(50),
Rua VARCHAR(100),
Numero INTEGER,
DuracaoConsultas SMALLDATETIME,
FOREIGN KEY(CBO) REFERENCES Especialidades (CBO) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE Exames (
IDpaciente INTEGER,
CRM VARCHAR(10),
IDexame INTEGER,
DataHora VARCHAR(10),
DataHoraFim DATETIME,
Valor DECIMAL(2),
Status INTEGER,
PRIMARY KEY(IDpaciente,CRM,IDexame,DataHora),
FOREIGN KEY(IDpaciente) REFERENCES Pacientes (IDpaciente) ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY(CRM) REFERENCES Medicos (CRM) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(IDexame) REFERENCES TipoExames (IDexame) ON UPDATE RESTRICT ON DELETE RESTRICT
)

CREATE TABLE Consultas (
CRM VARCHAR(10),
IDpaciente INTEGER,
DataHora DATETIME,
DataHoraFim DATETIME,
Valor DECIMAL(2),
Status INTEGER,
PRIMARY KEY(CRM,IDpaciente,DataHora),
FOREIGN KEY(CRM) REFERENCES Medicos (CRM) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(IDpaciente) REFERENCES Pacientes (IDpaciente) ON UPDATE RESTRICT ON DELETE RESTRICT
)

CREATE TABLE FormasPagamento (
IDformaPag INTEGER PRIMARY KEY,
Descricao VARCHAR(20)
)

ALTER TABLE Pacientes ADD FOREIGN KEY(IDformaPag) REFERENCES FormasPagamento (IDformaPag) ON UPDATE RESTRICT ON DELETE RESTRICT
